language: objective-c
sudo: false
cache: cocoapods
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
matrix:
  include:
    - osx_image: xcode9.3
      env: RFCI_TASK="POD_LINT"
before_install:
  - pod repo update master --silent
script: travis_wait ./.travis.sh MAIN
after_success: ./.travis.sh SUCCESS
after_failure: ./.travis.sh FAILURE
