name: CocoaPods

on: [push, pull_request]

jobs:
  lint:
    if: ${{ startsWith(github.ref, 'refs/heads') }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint the podspec
        run: |
          pod lib lint --fail-fast --allow-warnings

  release:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    runs-on: macos-latest
    env:
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Release the podspec
        run: |
          pod trunk push "RFAlpha.podspec"
